Repository NOWUM/EnSysMod, pull requests merged in 2021-12, with the labels that each got.

#21 Changed path for code coverage to ./ensysmod
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
Labels: github_actions

#22 Added docker and continuous deploy
  .github/workflows/main.yml
  .github/workflows/pull-request-done.yml
  .github/workflows/pull-request.yml
  Dockerfile
Labels: enhancement

#23 Fixed branch reference for development deployment
  .github/workflows/main.yml
  .github/workflows/pull-request-done.yml
Labels: github_actions

#29 Improve project appearance
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  README.md
  docs/source/conf.py
  docs/source/modelUser.rst
  docs/source/usage.rst
  ensysmod/core/config.py
  scripts/lint.sh
  setup.py
Labels: documentation

#28 Fixed ci/cd concurrency problems
  .github/workflows/main.yml
  .github/workflows/pull-request-done.yml
  .github/workflows/pull-request.yml
Labels: github_actions

#36 Improve CI/CD experience
  .github/workflows/main.yml
  .github/workflows/pull-request-done.yml
  .github/workflows/release-branch-create.yml
Labels: github_actions

#37 Fix release script grep error
  scripts/install.sh
  scripts/lint.sh
  scripts/release.sh
  scripts/run.sh
  scripts/test.sh
Labels: github_actions

#48 Added docker prune on deploy
  .github/workflows/main.yml
  .github/workflows/pull-request-done.yml
  .github/workflows/pull-request.yml
Labels: github_actions

#47 Improved crud repositories
  ensysmod/api/endpoints/ts_capacity_max.py
  ensysmod/api/endpoints/ts_operation_rate_fix.py
  ensysmod/api/endpoints/ts_operation_rate_max.py
  ensysmod/crud/base.py
  ensysmod/crud/base_depends_component.py
  ensysmod/crud/base_depends_dataset.py
  ensysmod/crud/base_depends_timeseries.py
  ensysmod/crud/energy_commodity.py
  ensysmod/crud/energy_component.py
  ensysmod/crud/energy_conversion.py
  ensysmod/crud/energy_sink.py
  ensysmod/crud/energy_source.py
  ensysmod/crud/energy_storage.py
  ensysmod/crud/energy_transmission.py
  ensysmod/crud/region.py
  ensysmod/crud/ts_capacity_max.py
  ensysmod/crud/ts_operation_rate_fix.py
  ensysmod/crud/ts_operation_rate_max.py
  ensysmod/schemas/base_ref_component_region.py
  tests/api/test_ts_capacity_max.py
  tests/api/test_ts_operation_rate_fix.py
  tests/api/test_ts_operation_rate_max.py
Labels: enhancement, code quality

#44 Added energy model
  ensysmod/api/api.py
  ensysmod/api/endpoints/energy_models.py
  ensysmod/crud/__init__.py
  ensysmod/crud/energy_model.py
  ensysmod/model/__init__.py
  ensysmod/model/energy_model.py
  ensysmod/schemas/__init__.py
  ensysmod/schemas/energy_model.py
  tests/api/test_energy_models.py
  tests/database/test_tables.py
  tests/utils/data_generator/__init__.py
  tests/utils/data_generator/energy_models.py
Labels: enhancement

#49 Fixed db query filter
  ensysmod/crud/base_depends_dataset.py
  ensysmod/crud/base_depends_timeseries.py
  tests/utils/data_generator/energy_conversions.py
  tests/utils/data_generator/energy_sinks.py
  tests/utils/data_generator/energy_sources.py
  tests/utils/data_generator/energy_storages.py
  tests/utils/data_generator/energy_transmissions.py
Labels: fix

#54 Added documentation for dataset creation
  docs/source/endpoints.rst
  docs/source/index.rst
  docs/source/usage.rst
  docs/source/usage/1_installation.rst
  docs/source/usage/2_dataset.rst
  docs/source/usage/3_model.rst
  docs/source/usage/execute.rst
  docs/source/usage/output.rst
Labels: documentation

#58 Added always condition for test and coverage result upload
  .github/workflows/pull-request.yml
Labels: github_actions
